server:
  port: 8084

spring:
  application:
    name: ai-engine-service
  data:
    redis:
      host: localhost
      port: 6379
  ai:
    google:
      genai:
        api-key: 1

# Tắt tạm logging rác của các thư viện, chỉ hiện log của thư mục com.voxnovel (thay bằng package name của bạn)
logging:
  level:
    root: INFO
# Khai báo danh sách các Key (Lấy từ biến môi trường)
vox-novel:
  ai-engine-service:
    keys:  1, 2, 3