server:
  port: 8084

spring:
  application:
    name: ai-engine-service
  data:
    redis:
      host: localhost
      port: 6379
  ai:
    google:
      genai:
          api-key: ${GOOGLE_GENAI_API_KEY}

# Tắt tạm logging rác của các thư viện, chỉ hiện log của thư mục com.voxnovel (thay bằng package name của bạn)
logging:
  level:
    root: INFO
# Khai báo danh sách các Key (Lấy từ biến môi trường)
vox-novel:
  ai-engine-service:
    keys: ${AI_ENGINE_KEYS}

rabbitmq:
  exchange: ai.exchange
  routing:
    request: ai.script.request
    response: ai.script.response
  queue:
    request: ai.script.generate.request.queue
    response: ai.script.generate.response.queue

feign:
  core-content-service:
    url: http://localhost:8082