server:
  port: 8085
spring:
  application:
    name: media-tts-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Cấu hình Custom cho Service của chúng ta
voxnovel:
  minio:
    endpoint: http://localhost:9000
    access-key: root_admin
    secret-key: root_password_123
    bucket-name: voxnovel-audio


#    Có thể cho nhiều API KEY VÀO ĐỂ CHẠY ĐA LUỒNG
  tts:
    providers:
      fpt:
        api-keys:
          - ${FPT_TTS_API_KEY_1}
          - ${FPT_TTS_API_KEY_2}
      cambai:
        api-keys:
          - ${CAMBAI_TTS_API_KEY_1}
          - ${CAMBAI_TTS_API_KEY_2}


rabbitmq:
  media:
    exchange: media.exchange
    routing:
      tts-request: media.tts.request
      tts-response: media.tts.response
      merge-request: media.merge.request
      merge-response: media.merge.response
    queue:
      tts-request: media.tts.generate.request.queue
      tts-response: media.tts.generate.response.queue
      merge-request: media.merge.request.queue
      merge-response: media.merge.response.queue



feign:
  core-content-service:
    url: http://localhost:8082
