server:
  port: 8082

spring:
  application:
    name: core-content-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    # Tự động kết nối lại nếu rớt mạng
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        max-attempts: 3
        max-interval: 10000ms


  datasource:
    url: jdbc:postgresql://localhost:5432/novel_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Định nghĩa các hằng số cho RabbitMQ
rabbitmq:
  exchange: ai.exchange
  routing:
    request: ai.script.request
    response: ai.script.response
  queue:
    request: ai.script.generate.request.queue
    response: ai.script.generate.response.queue