services:
  minio:
    image: quay.io/minio/minio
    container_name: voxnovel_minio
    ports:
      - "9000:9000"   # Port API cho AWS S3 SDK
      - "9001:9001"   # Port Admin Console
    environment:
      MINIO_ROOT_USER: root_admin
      MINIO_ROOT_PASSWORD: root_password_123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped

volumes:
  rabbitmq_data:
  minio_data: